redis:
  hosts:
    redis-1:
      ansible_host: 192.168.108.11
      ansible_port: 22
      ansible_user: vm1
postgresql:
  hosts:
    postgresql-1:
      ansible_host: 192.168.108.173
      ansible_port: 22
      ansible_user: vm1
poll:
  hosts:
    poll-1:
      ansible_host: 192.168.108.109
      ansible_port: 22
      ansible_user: vm1
result:
  hosts:
    result-1:
      ansible_host: 192.168.108.142
      ansible_port: 22
      ansible_user: vm1
worker:
  hosts:
    worker-1:
      ansible_host: 192.168.108.104
      ansible_port: 22
      ansible_user: vm1