- name: Import Postgres repo signing key
  become: True
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add postgresql 16 package repo
  become: True
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main
    update_cache: yes

- name: Install postgresql and tools
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - postgresql-16
    - postgresql-client-16
    - postgresql-contrib-16
    - acl
    - python3-psycopg2

- name: Upload configuration file
  become: true
  template:
    src: ../files/pg_hba.conf
    dest: /etc/postgresql/16/main/pg_hba.conf

- name: Set listen to all interface
  become: true
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    line: "listen_addresses = '*'"
    state: present

- name: Start pgsql service
  become: True
  service:
    name: postgresql@16-main
    enabled: yes
    state: restarted
    daemon_reload: true

- name: Copy db on target machine
  become: true
  template:
    src: ../files/schema.sql
    dest: /tmp/schema.sql

- name: Create paul database
  become: true
  become_method: sudo
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db }}"
    state: present

- name: Create schema on paul database
  become: true
  become_method: sudo
  become_user: postgres
  community.postgresql.postgresql_script:
    db: "{{ postgresql_db }}"
    path: /tmp/schema.sql

- name: Create paul user/password
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_user:
    db: "{{ postgresql_db }}"
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_pass }}"
    encrypted: yes
    state: present

- name: Set permission to user
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_privs:
    db: "{{ postgresql_db }}"
    state: present
    privs: SELECT
    type: table
    obj: votes
    role: "{{ postgresql_user }}"
